import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider, useAuth } from "./context/auth";
import MainLayout from "./MainLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "WAMMANDE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row h-screen">
          <AuthProvider>
            <MainLayout>{children}</MainLayout>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
